name: bluefin-opinionated
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - fish
      - starship
      - neovim
      - vim
      - emacs
      - waydroid
      - podman
      - podman-docker
      - podman-compose
      - distrobox
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true 
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      repo-url: https://nightly.gnome.org/gnome-nightly.flatpakrepo
      repo-name: gnome-nightly
      repo-title: "Gnome Nightly (system-wide)"
      install:
         - io.freetubeapp.FreeTube
         - one.ablaze.floorp
         - dev.vencord.Vesktop
         - md.obsidian.Obsidian
         - com.visualstudio.code
         - io.github.giantpinkrobots.flatsweep
         - io.github.prateekmedia.appimagepool
         - io.github.shiftey.Desktop
         - io.github.dvlv.boxbuddyrs
         - io.podman_desktop.PodmanDesktop
         - org.telegram.desktop
         - com.github.tchx84.Flatseal
         - org.gnome.Ptyxis.Devel
      remove:
      # - org.gnome.eog

  - type: signing
