name: bluefin-opinionated
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr
 
# - type: rpm-ostree
#    repo:
#    - #https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-40&arch=x86_64 #
#   -#  #https://mirrors.fedoraproject.org/mirrorlist?repo=updates-released-f40&#arch=x86_64
#    -  #https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS #_VERSION%/atim-starship-fedora-40.repo
#
#    install:
#     - fish
#     - neovim
#     - vim
#     - emacs
#     - waydroid
#     - podman
#     - podman-docker
#     - podman-compose
#     - distrobox
#
  - type: default-flatpaks
    notify: true 
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
    system:
      repo-url: https://nightly.gnome.org/gnome-nightly.flatpakrepo
      repo-name: gnome-nightly
      repo-title: "Gnome Nightly (system-wide)"
    system:
      repo-url: oci+https://registry.fedoraproject.org
      repo-name: fedora-curated
      repo-title: "Fedora flatpaks (system-wide)"
      install:
         - io.freetubeapp.FreeTube
         - one.ablaze.floorp
         - dev.vencord.Vesktop
         - md.obsidian.Obsidian
         - com.github.johnfactotum.Foliate
         - io.github.giantpinkrobots.flatsweep
         - io.github.prateekmedia.appimagepool
         - io.github.shiftey.Desktop
         - io.github.dvlv.boxbuddyrs
         - io.podman_desktop.PodmanDesktop
         - org.telegram.desktop
         - com.github.tchx84.Flatseal
         - org.gnome.Ptyxis.Devel
      remove:
         - org.mozilla.Firefox

  - type: signing
